package github

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/OkadaSatoshi/codingworker/worker/internal/config"
	"github.com/OkadaSatoshi/codingworker/worker/internal/retry"
	"github.com/OkadaSatoshi/codingworker/worker/internal/sqs"
)

// Client handles GitHub operations
type Client struct {
	config config.GitHubConfig
}

// NewClient creates a new GitHub client
func NewClient(cfg config.GitHubConfig) *Client {
	return &Client{
		config: cfg,
	}
}

// CloneAndBranch clones a repository and creates a new branch
func (c *Client) CloneAndBranch(ctx context.Context, repository string, issueNumber int) (string, error) {
	// Create work directory
	workDir := filepath.Join(c.config.CloneBaseDir, fmt.Sprintf("issue-%d-%d", issueNumber, time.Now().Unix()))
	if err := os.MkdirAll(workDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create work directory: %w", err)
	}

	// Clone repository
	repoURL := fmt.Sprintf("https://github.com/%s.git", repository)
	if c.config.Token != "" {
		repoURL = fmt.Sprintf("https://%s@github.com/%s.git", c.config.Token, repository)
	}

	slog.Info("Cloning repository", "repository", repository, "work_dir", workDir)

	cmd := exec.CommandContext(ctx, "git", "clone", "--depth", "1", repoURL, workDir)
	if output, err := cmd.CombinedOutput(); err != nil {
		wrapped := retry.WrapWithClassification(err, string(output))
		return "", fmt.Errorf("git clone failed: %w, output: %s", wrapped, string(output))
	}

	// Create and checkout new branch
	branchName := fmt.Sprintf("auto-code/issue-%d", issueNumber)
	cmd = exec.CommandContext(ctx, "git", "checkout", "-b", branchName)
	cmd.Dir = workDir
	if output, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git checkout failed: %w, output: %s", err, string(output))
	}

	slog.Info("Branch created", "branch", branchName)
	return workDir, nil
}

// PushAndCreatePR pushes changes and creates a pull request
func (c *Client) PushAndCreatePR(ctx context.Context, workDir string, msg *sqs.Message) (string, error) {
	// Get branch name
	cmd := exec.CommandContext(ctx, "git", "branch", "--show-current")
	cmd.Dir = workDir
	branchOutput, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("failed to get branch name: %w", err)
	}
	branchName := strings.TrimSpace(string(branchOutput))

	// Check if there are changes to commit
	cmd = exec.CommandContext(ctx, "git", "status", "--porcelain")
	cmd.Dir = workDir
	statusOutput, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git status failed: %w", err)
	}

	if len(statusOutput) == 0 {
		slog.Warn("No changes to commit")
		return "", fmt.Errorf("no changes generated by Aider")
	}

	// Push branch
	slog.Info("Pushing branch", "branch", branchName)
	cmd = exec.CommandContext(ctx, "git", "push", "-u", "origin", branchName)
	cmd.Dir = workDir
	if output, err := cmd.CombinedOutput(); err != nil {
		wrapped := retry.WrapWithClassification(err, string(output))
		return "", fmt.Errorf("git push failed: %w, output: %s", wrapped, string(output))
	}

	// Create PR using gh CLI
	prTitle := fmt.Sprintf("[auto-code] %s", msg.Title)
	prBody := c.buildPRBody(msg)

	slog.Info("Creating pull request", "title", prTitle)
	cmd = exec.CommandContext(ctx, "gh", "pr", "create",
		"--title", prTitle,
		"--body", prBody,
		"--head", branchName,
	)
	cmd.Dir = workDir
	prOutput, err := cmd.CombinedOutput()
	if err != nil {
		wrapped := retry.WrapWithClassification(err, string(prOutput))
		return "", fmt.Errorf("gh pr create failed: %w, output: %s", wrapped, string(prOutput))
	}

	prURL := strings.TrimSpace(string(prOutput))
	return prURL, nil
}

// AddComment adds a comment to an issue
func (c *Client) AddComment(ctx context.Context, repository string, issueNumber int, body string) error {
	// Use gh CLI to add comment
	cmd := exec.CommandContext(ctx, "gh", "issue", "comment",
		fmt.Sprintf("%d", issueNumber),
		"--repo", repository,
		"--body", body,
	)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh issue comment failed: %w, output: %s", err, string(output))
	}

	slog.Info("Comment added to issue", "repository", repository, "issue", issueNumber)
	return nil
}

// buildPRBody creates the PR description
func (c *Client) buildPRBody(msg *sqs.Message) string {
	return fmt.Sprintf(`## 自動生成されたコード

このPRは CodingWorker によって自動生成されました。

**関連Issue**: #%d
**生成モデル**: Ollama qwen2.5-coder:1.5b (via Aider)
**生成日時**: %s
**生成方式**: 2パス（実装 + テスト自動生成）

### タスク内容
%s

### 自動検証結果
- [x] ビルド成功 (go build)
- [x] Lint通過 (go fmt, go vet)
- [x] テスト通過 (go test)

### 確認事項
- [ ] コードが期待通りに動作するか
- [ ] テストカバレッジが十分か
`,
		msg.IssueNumber,
		time.Now().Format("2006-01-02 15:04:05"),
		msg.Body,
	)
}
