version: '3'

vars:
  BINARY_NAME: codingworker
  BUILD_DIR: ./bin

tasks:
  # =============================================================================
  # Build
  # =============================================================================
  build:
    desc: バイナリをビルド
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - mise exec -- go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/worker
      - mise exec -- go build -o {{.BUILD_DIR}}/inject ./cmd/inject
    sources:
      - ./**/*.go
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"
      - "{{.BUILD_DIR}}/inject"

  # =============================================================================
  # Run
  # =============================================================================
  run:
    desc: Workerを実行
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:dev:
    desc: 開発モードで実行（ビルドなし）
    cmds:
      - mise exec -- go run ./cmd/worker

  run:test:
    desc: テストメッセージで実行
    deps: [build]
    cmds:
      - |
        if [ ! -f testdata/message.json ]; then
          echo "Error: testdata/message.json not found"
          echo "Run 'task inject:create' first"
          exit 1
        fi
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}} -test-message testdata/message.json -log-level debug"

  # =============================================================================
  # Inject (Test Message)
  # =============================================================================
  inject:create:
    desc: テストメッセージを作成
    deps: [build]
    cmds:
      - mkdir -p testdata
      - |
        {{.BUILD_DIR}}/inject \
          -repo "{{.TEST_REPO | default "OkadaSatoshi/codingworker-sandbox"}}" \
          -issue {{.TEST_ISSUE | default 1}} \
          -title "{{.TEST_TITLE | default "Create hello.go"}}" \
          -body "{{.TEST_BODY | default "Create a simple hello world program in Go"}}" \
          -output testdata/message.json
      - echo "Test message created at testdata/message.json"

  inject:show:
    desc: テストメッセージを表示
    cmds:
      - cat testdata/message.json 2>/dev/null || echo "No test message found. Run 'task inject:create' first"

  # =============================================================================
  # Test
  # =============================================================================
  test:
    desc: テストを実行
    cmds:
      - mise exec -- go test -v ./...

  test:coverage:
    desc: カバレッジ付きでテストを実行
    cmds:
      - mise exec -- go test -v -coverprofile=coverage.out ./...
      - mise exec -- go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  # =============================================================================
  # Setup
  # =============================================================================
  setup:
    desc: 初期セットアップ（config作成 + 依存関係）
    cmds:
      - task: setup:config
      - task: deps

  setup:config:
    desc: 設定ファイルを作成（config.yaml.sample → config.yaml）
    cmds:
      - |
        if [ -f configs/config.yaml ]; then
          echo "configs/config.yaml already exists. Skipping."
        else
          cp configs/config.yaml.sample configs/config.yaml
          echo "Created configs/config.yaml from sample."
          echo "Edit configs/config.yaml to customize settings (e.g., model name)."
        fi
    status:
      - test -f configs/config.yaml

  # =============================================================================
  # Dependencies
  # =============================================================================
  deps:
    desc: 依存関係をダウンロード
    cmds:
      - mise exec -- go mod download
      - mise exec -- go mod tidy

  # =============================================================================
  # Clean
  # =============================================================================
  clean:
    desc: ビルド成果物を削除
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  # =============================================================================
  # Lint
  # =============================================================================
  lint:
    desc: コードをリント
    cmds:
      - |
        if command -v golangci-lint &> /dev/null; then
          golangci-lint run
        else
          echo "[WARN] golangci-lint not installed. Run: brew install golangci-lint"
        fi

  # =============================================================================
  # Verify
  # =============================================================================
  verify:
    desc: 依存ツールの確認
    cmds:
      - |
        echo "=== Checking dependencies ==="
      - |
        echo -n "Go: "
        mise exec -- go version
      - |
        echo -n "Aider: "
        if [ -f ~/.local/bin/aider ]; then
          ~/.local/bin/aider --version
        else
          echo "NOT FOUND"
        fi
      - |
        echo -n "Ollama: "
        if command -v ollama &> /dev/null; then
          ollama --version
        else
          echo "NOT FOUND"
        fi
      - |
        echo -n "gh CLI: "
        if command -v gh &> /dev/null; then
          gh --version | head -1
        else
          echo "NOT FOUND"
        fi
      - echo "=== Done ==="
